### ISSUE TITLE
trial comet failed

### ISSUE THREAD

**Issue by charlyms** [jdswinbank/Comet#47]
Hello, I try to get Comet work, but the trial failed:

charlyms@ubuntu:~$ trial comet
comet.handler.test.test_relay
  EventRelayTestCase
    test_interface ...                                                     [OK]
    test_name ...                                                          [OK]
    test_send_event ...                                                    [OK]
comet.handler.test.test_spawn
  SpawnCommandProtocolTestCase
    test_bad_process ...                                                   [OK]
    test_good_process ...                                                  [OK]
    test_interface ...                                                     [OK]
    test_write_data ...                                                    [OK]
comet.log.test.test_log
  test_comet_logging
    test_default_level ...                                                 [OK]
    test_log_debug_level_debug ...                                         [OK]
    test_log_debug_level_info ...                                          [OK]
    test_log_debug_level_warning ...                                       [OK]
    test_log_info_level_debug ...                                          [OK]
    test_log_info_level_info ...                                           [OK]
    test_log_info_level_warning ...                                        [OK]
    test_log_warning_level_debug ...                                       [OK]
    test_log_warning_level_info ...                                        [OK]
    test_log_warning_level_warning ...                                     [OK]
comet.plugins.test.test_eventprinter
  EventPrinterTestCase
    test_interface ...                                                     [OK]
    test_name ...                                                          [OK]
    test_print_event ...                                                   [OK]
comet.plugins.test.test_eventwriter
  EventFileTestCase
    test_dup_file ...                                                      [OK]
    test_file_contents ...                                                 [OK]
    test_file_created ...                                                  [OK]
    test_temp_dir ...                                                      [OK]
  EventWriterTestCase
    test_create_directory ...                                              [OK]
    test_custom_directory ...                                              [OK]
    test_interface ...                                                     [OK]
    test_name ...                                                          [OK]
    test_save_event ...                                                    [OK]
  StringToFilenameTestCase
    test_characters ...                                                    [OK]
comet.protocol.test.test_base
  ElementSenderTestCase
    test_lengthLimitExceeded ...                                           [OK]
    test_send_xml ...                                                      [OK]
  EventHandlerTestCase
    test_handle_event_fails ...                                            [OK]
    test_handle_event_succeeds ...                                         [OK]
    test_process_event_invalid_can_nak ...                                 [OK]
    test_process_event_invalid_cant_nak ...                                [OK]
    test_process_event_valid_fails ...                                     [OK]
    test_process_event_valid_succeeds ...                                  [OK]
    test_validate_event_invalid ...                                        [OK]
    test_validate_event_valid ...                                          [OK]
comet.protocol.test.test_messages
  TransportTestCase
    test_ack_valid ...                                                     [OK]
    test_authenticate_valid ...                                            [OK]
    test_authenticateresponse_valid ...                                    [OK]
    test_authenticateresponse_valid_filter ...                             [OK]
    test_iamalive_valid ...                                                [OK]
    test_iamaliveresponse_valid ...                                        [OK]
    test_nak_valid ...                                                     [OK]
    test_nak_with_result_valid ...                                         [OK]
comet.protocol.test.test_voeventbroadcaster
  VOEventBroadcasterFactoryNoTestEventsTestCase
    test_DoNotSendTestEvent ...                                            [OK]
  VOEventBroadcasterFactoryTestCase
    test_protocol ...                                                      [OK]
    test_sendIamAlive ...                                                  [OK]
    test_sendTestEvent ...                                                 [OK]
  VOEventBroadcasterTestCase
    test_alive_timeout ...                                                 [OK]
    test_lack_of_ack ...                                                   [OK]
    test_receive_ack ...                                                   [OK]
    test_receive_authenticateresponse_legacy ...                           [OK]
    test_receive_authenticateresponse_with_bad_filter ...                  [OK]
    test_receive_authenticateresponse_with_filters ...                     [OK]
    test_receive_iamalive ...                                              [OK]
    test_receive_incomprehensible ...                                      [OK]
    test_receive_nak ...                                                   [OK]
    test_receive_unparsable ...                                            [OK]
    test_register_broadcaster ...                                          [OK]
    test_sendIAmAlive ...                                                  [OK]
    test_send_event ...                                                    [OK]
    test_send_event_with_filter_accept ...                                 [OK]
    test_send_event_with_filter_reject ...                                 [OK]
    test_sent_authenticate ...                                             [OK]
comet.protocol.test.test_voeventreceiver
  VOEventReceiverFactoryTestCase
    test_contents ...                                                      [OK]
    test_protocol ...                                                      [OK]
  VOEventReceiverTestCase
    test_receive_incomprehensible ...                                      [OK]
    test_receive_unparsable ...                                            [OK]
    test_receive_voevent ...                                               [OK]
    test_receive_voevent_invalid ...                                       [OK]
    test_timeout ...                                                       [OK]
comet.protocol.test.test_voeventsender
  VOEventSenderFactoryTestCase
    test_no_ack ...                                                        [OK]
    test_protocol ...                                                      [OK]
    test_stored_event ...                                                  [OK]
  VOEventSenderTestCase
    test_connectionMade ...                                                [OK]
    test_receive_ack ...                                                   [OK]
    test_receive_incomprehensible ...                                      [OK]
    test_receive_nak ...                                                   [OK]
    test_receive_unparsable ...                                            [OK]
comet.protocol.test.test_voeventsubscriber
  VOEventSubscriberFactoryTestCase
    test_protocol ...                                                      [OK]
    test_reconnect_delay ...                                               [OK]
  VOEventSubscriberTestCase
    test_receive_authenticate ...                                          [OK]
    test_receive_iamalive ...                                              [OK]
    test_receive_incomprehensible ...                                      [OK]
    test_receive_invalid_voevent ...                                       [OK]
    test_receive_unparsable ...                                            [OK]
    test_receive_valid_voevent ...                                         [OK]
  VOEventSubscriberTimeoutTestCase
    test_timeout ...                                                       [OK]
comet.service.test.test_broker
  DefaultOptionsTestCase
    test_action_non_extant ...                                             [OK]
    test_args_for_disabled_plugin ...                                   [ERROR]
    test_cmd ...                                                        [ERROR]
    test_default_broadcast_whitelist ...                                [ERROR]
    test_default_submission_whitelist ...                               [ERROR]
    test_enable_broadcast ...                                           [ERROR]
    test_enable_receive ...                                             [ERROR]
    test_faulty_cmd_line ...                                               [OK]
    test_filters ...                                                    [ERROR]
    test_has_print_event_plugin ...                                     [ERROR]
    test_has_save_event_plugin ...                                      [ERROR]
    test_invalid_filter ...                                                [OK]
    test_invalid_ivorn ...                                                 [OK]
    test_ivorn_missing ...                                                 [OK]
    test_populated_broadcast_whitelist ...                              [ERROR]
    test_populated_submission_whitelist ...                             [ERROR]
    test_remotes ...                                                    [ERROR]
    test_save_event_plugin_takes_args ...                               [ERROR]
    test_test_event_loop ...                                            [ERROR]
    test_valid_ivorn ...                                                [ERROR]
    test_verbose_contradictory ...                                      [ERROR]
    test_verbose_default ...                                            [ERROR]
    test_verbose_quiet ...                                              [ERROR]
    test_verbose_verbose ...                                            [ERROR]
  ServiceTestCase
    test_has_receiver ...                                               [ERROR]
    test_no_service ...                                                 [ERROR]
comet.utility.test.test_event_db
  Event_DB_TestCase
    test_bad_ivorn ...                                                     [OK]
    test_prune ...                                                         [OK]
    test_prune_bad_event ...                                               [OK]
    test_seen ...                                                          [OK]
    test_threadsafe ...                                                    [OK]
    test_unseen ...                                                        [OK]
comet.utility.test.test_voevent
  broker_test_messageTestCase
    test_valid ...                                                         [OK]
  parse_ivornTestCase
    test_authority_id ...                                                  [OK]
    test_fragment ...                                                      [OK]
    test_no_fragment ...                                                   [OK]
    test_partial_ivorn ...                                                 [OK]
    test_resource_key ...                                                  [OK]
    test_simple ...                                                        [OK]
comet.utility.test.test_whitelist
  WhitelistingFactoryTestCase
    test_empty_whitelist ...                                            [ERROR]
    test_in_whitelist ...                                               [ERROR]
    test_log_message ...                                                [ERROR]
    test_not_in_whitelist ...                                           [ERROR]
comet.utility.test.test_xml
  mutable_element_tests
    test_transform_element ...                                             [OK]
    test_transform_text ...                                                [OK]
  xml_document_encoding
    test_encoding_detection ...                                            [OK]
    test_from_unicode ...                                                  [OK]
  xml_document_from_element_TestCase
    test_element ...                                                       [OK]
    test_signature ...                                                     [OK]
    test_text ...                                                          [OK]
  xml_document_from_string_TestCase
    test_element ...                                                       [OK]
    test_signature ...                                                     [OK]
    test_text ...                                                          [OK]
  xml_security_TestCase
    test_billion_laughs ...                                                [OK]
    test_quadratic_blowup ...                                              [OK]
comet.validator.test.test_ivorn
  CheckSchemaTestCase
    test_interface ...                                                     [OK]
    test_invalid ...                                                       [OK]
    test_valid ...                                                         [OK]
comet.validator.test.test_previously_seen
  CheckPreviouslySeenTestCase
    test_db_failure ...                                                    [OK]
    test_interface ...                                                     [OK]
    test_previously_checked ...                                            [OK]
    test_unseen ...                                                        [OK]
comet.validator.test.test_schema
  CheckSchemaTestCase
    test_interface ...                                                     [OK]
    test_invalid ...                                                       [OK]
    test_valid ...                                                         [OK]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 108, in test_args_for_disabled_plugin
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_args_for_disabled_plugin
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 127, in test_cmd
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_cmd
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 65, in test_default_broadcast_whitelist
    self._test_empty_whitelist('subscriber-whitelist')
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 61, in _test_empty_whitelist
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_default_broadcast_whitelist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 68, in test_default_submission_whitelist
    self._test_empty_whitelist('author-whitelist')
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 61, in _test_empty_whitelist
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_default_submission_whitelist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 48, in test_enable_broadcast
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_enable_broadcast
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 42, in test_enable_receive
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_enable_receive
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 118, in test_filters
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_filters
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 89, in test_has_print_event_plugin
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_has_print_event_plugin
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 95, in test_has_save_event_plugin
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_has_save_event_plugin
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 82, in test_populated_broadcast_whitelist
    self._test_populated_whitelist('subscriber-whitelist')
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 74, in _test_populated_whitelist
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 255, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 112, in opt_subscriber_whitelist
    self['running_subscriber-whitelist'].append(ip_network(network, strict=False))
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '1.2.3.4/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_populated_broadcast_whitelist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 85, in test_populated_submission_whitelist
    self._test_populated_whitelist('author-whitelist')
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 74, in _test_populated_whitelist
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 255, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 108, in opt_author_whitelist
    self['running_author-whitelist'].append(ip_network(network, strict=False))
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '1.2.3.4/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_populated_submission_whitelist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 55, in test_remotes
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_remotes
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 101, in test_save_event_plugin_takes_args
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_save_event_plugin_takes_args
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 36, in test_test_event_loop
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_test_event_loop
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 150, in test_valid_ivorn
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_valid_ivorn
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 146, in test_verbose_contradictory
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_verbose_contradictory
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 131, in test_verbose_default
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_verbose_default
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 141, in test_verbose_quiet
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_verbose_quiet
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 136, in test_verbose_verbose
    self.config.parseOptions(self.cmd_line)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.DefaultOptionsTestCase.test_verbose_verbose
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 171, in test_has_receiver
    '-b', '--remote', 'dummy'])
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 166, in _make_service
    self.config.parseOptions(options)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.ServiceTestCase.test_has_receiver
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 194, in test_no_service
    service = self._make_service(['--local-ivo', 'ivo://comet/test'])
  File "/usr/local/lib/python2.7/dist-packages/comet/service/test/test_broker.py", line 166, in _make_service
    self.config.parseOptions(options)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.7/dist-packages/comet/service/broker.py", line 119, in postOptions
    self['author-whitelist'] = [ip_network(self['author-whitelist'], strict=False)]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.service.test.test_broker.ServiceTestCase.test_no_service
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/test/test_whitelist.py", line 30, in test_empty_whitelist
    factory.buildProtocol(IPv4Address('TCP', '127.0.0.1', 0)),
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/whitelist.py", line 17, in buildProtocol
    remote_ip = ip_address(addr.host)
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
ipaddress.AddressValueError: '127.0.0.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.utility.test.test_whitelist.WhitelistingFactoryTestCase.test_empty_whitelist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/test/test_whitelist.py", line 38, in test_in_whitelist
    factory = WhitelistingFactory(TestFactory(), [ip_network('0.0.0.0/0')])
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.utility.test.test_whitelist.WhitelistingFactoryTestCase.test_in_whitelist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/test/test_whitelist.py", line 57, in test_log_message
    TestFactory(), [ip_network('127.0.0.1/32')], TEST_STRING
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '127.0.0.1/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.utility.test.test_whitelist.WhitelistingFactoryTestCase.test_log_message
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/test/test_whitelist.py", line 47, in test_not_in_whitelist
    factory = WhitelistingFactory(TestFactory(), [ip_network('127.0.0.1/32')])
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '127.0.0.1/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.utility.test.test_whitelist.WhitelistingFactoryTestCase.test_not_in_whitelist
-------------------------------------------------------------------------------
Ran 157 tests in 1.182s

FAILED (errors=25, successes=132)
Can you please describe, what is going wrong here?
Regards from Germany
Charlyms

**Comment by jdswinbank** [comment]
I suspect the issue here is confusion over similarly-named modules. Unfortunately, [ipaddress](https://github.com/phihag/ipaddress) and [py2-ipaddress](https://bitbucket.org/kwi/py2-ipaddress/)  aren't compatible. Comet requires the latter (and that's what you should get if you follow the link in the README or `pip install -r requirements.txt`), but I bet you're trying to use the former.
Does that resolve the issue?

**Comment by charlyms** [comment]
Yes, it does!
Surpreisingly it only works when I start from commandline within the folder from wich I installed py2-ipaddress. The test runs without any probs.
Unfortunately I am not able to get further, your programm is too complicated for me to build a satisfying command. Blame it on me
Regards from Germany
Charlyms
