### ISSUE TITLE
ipaddress errors and trial comet failures

### ISSUE THREAD

**Issue by richardjamesw** [jdswinbank/Comet#49]
Hello,

I am running into a couple issues while trying to use Comet--

I run the below to receive events through Comet:
```
twistd -n comet --local-ivo=ivo://edu.oswego.team8/comet_broker  --remote=voevent.swinbank.org --save-event --save-event-directory=/home/richardjames/events -r
```

Unfortunately this is giving me the below error with ipaddress:
```
ipaddress.AddressValueError: '0.0.0.0/0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?
```

I have installed comet, however, when I run "trial comet" I get 25 failures here are a couple of the errors:
```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/test/test_whitelist.py", line 57, in test_log_message
    TestFactory(), [ip_network('127.0.0.1/32')], TEST_STRING
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '127.0.0.1/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.utility.test.test_whitelist.WhitelistingFactoryTestCase.test_log_message
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/comet/utility/test/test_whitelist.py", line 47, in test_not_in_whitelist
    factory = WhitelistingFactory(TestFactory(), [ip_network('127.0.0.1/32')])
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '127.0.0.1/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

comet.utility.test.test_whitelist.WhitelistingFactoryTestCase.test_not_in_whitelist
-------------------------------------------------------------------------------
Ran 157 tests in 4.891s

FAILED (errors=25, successes=132)
```

Thank You for any help!
-Rick W

**Comment by jdswinbank** [comment]
Looks like confusion between the annoyingly similarly named [ipaddress](https://github.com/phihag/ipaddress) and [py2-ipaddress](https://bitbucket.org/kwi/py2-ipaddress/) packages. You need the latter; the former won't work.

See also #47, #38 and probably others. I'll try and make this clearer in the documentation.

Does that help?

**Comment by richardjamesw** [comment]
Yes I believe I had both packages installed. There were two ipaddress.py files in my directory, after removing one I was able to get comet working. 

Thank You
