### ISSUE TITLE
automat error

### ISSUE THREAD

**Issue by benw1** [jdswinbank/Comet#53]
I get an error when running trial, which says automat is not there; however, automat is there.  Please see below:

trial comet
Traceback (most recent call last):
  File "/Users/ben/miniconda2/bin/trial", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/ben/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/Users/ben/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/Users/ben/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/Users/ben/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 662, in _build_master
  File "/Users/ben/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 675, in _build_from_requirements
  File "/Users/ben/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'Automat>=0.3.0' distribution was not found and is required by Twisted
$ sudo conda install automat
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.

**Comment by jdswinbank** [comment]
Hi @benw1,

This looks like some problem with the way Python is set up on your system; I don't think it's directly related to Comet, except insofar as Comet needs libraries which haven't been installed properly for some reason. If you can provide more details about how you've set things up, I'll be happy to try to help.

**Comment by jdswinbank** [comment]
I spoke to @benw1 about this in person today. Two outcomes:

1. I should provide a tested, Conda-based installation procedure in the Comet docs.
2. Comet does not currently install all of its test scripts, causing the test suite to fail when run against an installed Comet.

I'll fix issue 2 above on this ticket, and open another to document the Conda-based procedure.

For now, I think @benw1 is up & running.
